### ISSUE TITLE
Why would you need to open a switch?

### ISSUE THREAD

**Issue by moubry** [swill/builder-docs#3]
I'm a beginner with question when choosing between switch cutout styles. [From the docs](http://builder-docs.swillkb.com/features/#switch-type):

> The most popular MX specific cutout which allows for switch opening without desoldering from the PCB. It is the most stable openable MX cutout, but you will pay a little more to get a plate cut with this cutout than the previous cutout.

Why would someone want to be able to open the switch?

It might be useful for beginners like me if a sentence were added to this description that mentions why someone might want to open a switch, so that it's easier to make the decision about which switch cutout style to use. I'm trying to predict whether I'll ever want to open the switch in the future, or if this is something most people will never need to do.

Thank you so much for your work on swillkb --- it's amazing. I really appreciate it.

**Comment by swill** [comment]
The reason people want to have the option to open the switches is because it gives them the ability to do any/all of the following things:
- Change the springs. This is a very common adaptation people like to make. Everyone has their favorite spring weight and style.
- Lubercate the switches.  If you choose to do this, I recommend you do some research first. There are some specific products you will want to use and a process to follow when doing the work. This is usually done when people use very light springs in tactile switches. Something like an `ergo clear`, which is a MX clear switch with a 62g spring.
- Some dampening mods. I have done a mod where you put a small silicone ball inside the tube which the stem travels in. This means that the key bottoms out on a silicon ball rather than a the normal bottom out on plastic. This makes for a little softer bottom out and makes it quieter. 

So if you would want to do these types of switch mods without desoldering the whole board, then you want a switch cutout which supports opening. 

That help?

**Comment by moubry** [comment]
Wow, that was a better answer than I could have hoped for! You are amazing. Thank you.

**Comment by swill** [comment]
No problem.  Thank you for using and having an interest in my tool.  👍
